config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: %i[registrations sessions]
  devise_scope :user do
    authenticated :user do
      root 'wishlists#index'
    end

    unauthenticated do
      root 'public/wishlists#index'
    end
  end

  resources :wishlists, except: :show do
    resources :products, only: %i[index new create destroy],
                         module: 'wishlists' do
      post :create
    end
  end

  namespace :public do
    resources :wishlists, only: :index do
      resources :products, only: :index, module: 'wishlists'
    end

    resource :shopping_cart, only: :show do
      post :add_product
      post :checkout
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  belongs_to :parent, optional: true, class_name: 'Category'
  has_many :children, class_name: 'Category', foreign_key: 'parent_id'

  validates :name, uniqueness: true

  scope :top_level, -> { where(parent: nil) }

  def self_and_descendents_ids
    [id] + descendants_ids
  end

  def descendants_ids
    Category.where(parent: self).map do |child|
      [child.id] + child.descendants_ids
    end.flatten
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_wishlists, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/product_wishlist.rb
class ProductWishlist < ApplicationRecord
  belongs_to :product
  belongs_to :wishlist
  has_and_belongs_to_many :shopping_carts

  def can_be_destroyed?
    !bought?
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_and_belongs_to_many :product_wishlists

  def can_checkout?
    product_wishlists.any?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable

  has_many :wishlists, dependent: :destroy
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :product_wishlists, dependent: :destroy
  has_many :products, through: :product_wishlists

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_shopping_cart
  helper_method :current_shopping_cart

  private

  def set_shopping_cart
    if session[:shopping_cart_id]
      @current_shopping_cart = ShoppingCart.find_by(id: session[:shopping_cart_id])
      if @current_shopping_cart.nil?
        create_shopping_cart!
      end
    else
      create_shopping_cart!
    end
  end

  def create_shopping_cart!
    @current_shopping_cart = ShoppingCart.create!
    session[:shopping_cart_id] = @current_shopping_cart.id
  end

  def current_shopping_cart
    @current_shopping_cart
  end
end

app/controllers/wishlists/products_controller.rb
class Wishlists::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishlist
  before_action :set_categories, :set_filtered_by_category, only: %i[index new]

  def index
    collection = @wishlist.product_wishlists.includes(:product)
    @product_wishlists = FilterProductsByCategory.call(@filtered_by_category,
                                                       collection)
                                                 .order(:bought)
                                                 .paginate(page: params[:page],
                                                           per_page: 10)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @products = FilterProductsByCategory.call(@filtered_by_category,
                                              Product.all)
                                        .paginate(page: params[:page],
                                                  per_page: 10)
  end

  def create
    product = Product.find_by(id: params[:product_id])
    product_wishlist = @wishlist.product_wishlists.build(product: product)

    if product_wishlist.save
      redirect_to wishlist_products_path(@wishlist), notice: t('.success')
    else
      flash[:error] = t('.something_went_wrong')
      redirect_to wishlist_products_path(@wishlist)
    end
  end

  def destroy
    product_wishlist = @wishlist.product_wishlists.find(params[:id])

    if product_wishlist.can_be_destroyed?
      product_wishlist.destroy
      redirect_to wishlist_products_path(@wishlist), notice: t('.success')
    else
      redirect_to wishlist_products_path(@wishlist),
                  notice: t('.cannot_destroy_bought_product')
    end
  end

  private

  def set_wishlist
    @wishlist = current_user.wishlists.find(params[:wishlist_id])
  end

  def set_categories
    @categories = Category.top_level.includes(:children)
  end

  def set_filtered_by_category
    @filtered_by_category = Category.find_by(id: params[:filter_by_category])
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishlist, only: %i[edit update destroy]

  def index
    @wishlists = current_user.wishlists.paginate(page: params[:page])
  end

  def new
    @wishlist = current_user.wishlists.build
  end

  def create
    @wishlist = current_user.wishlists.build(wishlist_params)

    if @wishlist.save
      flash[:success] = t('.success')
      redirect_to wishlist_products_path(@wishlist)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @wishlist.update(wishlist_params)
      flash[:success] = t('.success')
      redirect_to wishlist_products_path(@wishlist)
    else
      render :edit
    end
  end

  def destroy
    @wishlist.destroy

    flash[:success] = t('.success')
    redirect_to wishlists_path
  end

  private

  def set_wishlist
    @wishlist = current_user.wishlists.find(params[:id])
  end

  def wishlist_params
    params.require(:wishlist).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(flash_type)
    case flash_type
    when 'success', 'notice'
      'alert-success'
    when 'error', 'alert'
      'alert-danger'
    else
      flash_type.to_s
    end
  end

  def menu_path(params)
    if current_page?(wishlist_products_path)
      wishlist_products_path(params)
    elsif current_page?(new_wishlist_product_path)
      new_wishlist_product_path(params)
    else
      public_wishlist_products_path(params)
    end
  end
end

app/views/layouts/_messages.html.slim
.container
  - flash.each do |type, msg|
    .alert.alert-dismissable.fade.show[class=flash_class(type)]
      = msg
      button.close[type="button" data-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"]
          | ×

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  .navbar-brand Gift Wishlist
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbar.collapse.navbar-collapse.text-white
    - if user_signed_in?
      ul.navbar-nav.mr-auto
        li= link_to t('.wishlists'), wishlists_path, class: 'nav-link'
      .ml-auto
        ul.navbar-nav.mr-auto
          li.nav-item= current_user.email

      .ml-2
        ul.navbar-nav.mr-auto
          li.nav-item
            = link_to t('.sign_out'), destroy_user_session_path,
                                      method: :delete,
                                      class: 'nav-link'
    - else
      ul.navbar-nav.mr-auto
        li= link_to t('.wishlists'), public_wishlists_path, class: 'nav-link'
      .ml-auto
        ul.navbar-nav.mr-auto
          li.nav-item= link_to public_shopping_cart_path, class: 'nav-link' do
            = t('.shopping_cart')
            '
            span.fa.fa-shopping-cart
          li.nav-item= link_to t('.sign_in'), new_user_session_path,
                                              class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gift Wishlist
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render partial: 'layouts/navbar'
    main
      = render partial: 'layouts/messages', flash: flash
      .container
        = yield

app/views/product_wishlists/_product_wishlist.html.slim
.card.product-card
  = image_tag('no-image', class: 'card-img-top product-image')
  .card-body
    .card-text
      small.text-truncate.product-name= product_wishlist.product.name
      p= number_to_currency(product_wishlist.product.price)
      - if current_shopping_cart&.product_wishlists&.include?(product_wishlist)
        span.badge.badge-warning= t('.in_cart')
      - elsif product_wishlist.bought
        span.badge.badge-success= t('.bought')
      - else
        span.badge.badge-dark= t('.available')
        - unless user_signed_in?
          = link_to t('.buy'),
                      add_product_public_shopping_cart_path(product_wishlist_id: product_wishlist.id),
                      method: :post,
                      class: 'float-right btn btn-sm btn-outline-success'
      - if user_signed_in?
        - unless product_wishlist.bought
          = link_to t('.delete'),
                    wishlist_product_path(product_wishlist,
                                          wishlist_id: @wishlist.id),
                    method: :delete,
                    class: 'float-right btn btn-sm btn-outline-danger'

app/views/product_wishlists/_product_wishlists.html.slim
- @product_wishlists.each do |product_wishlist|
  = render 'product_wishlists/product_wishlist',
           product_wishlist: product_wishlist

app/views/shared/_category_menu.html.slim
li.list-group-item
  = link_to category.name, menu_path(filter_by_category: category.id)
  - if category.children.any?
    = link_to '#', data: { toggle: 'collapse', target: "##{category.name.parameterize}" } do
      span.badge.badge-dark.float-right
        span.fa.fa-chevron-down.fa-menu

- if category.children.any?
  .list-group.list-group-child.collapse[id=category.name.parameterize]
    - category.children.each do |child|
      = render 'shared/category_menu', category: child

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .card.border-danger.mb-3
    .card-body.text-danger
      ul.mb-0
        - obj.errors.full_messages.each do |msg|
          li= msg

app/views/wishlists/_form.html.slim
= render 'shared/errors', obj: @wishlist

= form_for(@wishlist, html: { class: 'form-horizontal', role: 'form' }) do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  br
  = f.submit class: 'btn btn-primary'

app/views/wishlists/edit.html.slim
.row.justify-content-center
  .col-6
    h2= t('.edit_wishlist')

    = render partial: 'form'

app/views/wishlists/index.html.slim
h2.d-inline-block= t('.wishlists')
.float-right
  = link_to t('.new'), new_wishlist_path, class: 'btn btn-primary'
hr

table.table
  thead.thead-dark
    tr
      th= t('.name')
      th= t('.actions')
  tbody
    - @wishlists.each do |wishlist|
      tr
        td= wishlist.name
        td
          .btn-group.btn-group-sm
            = link_to t('.view'), wishlist_products_path(wishlist),
                                  class: 'btn btn-primary'
            = link_to t('.edit'), edit_wishlist_path(wishlist),
                                  class: 'btn btn-info'
            = link_to t('.delete'), wishlist_path(wishlist), method: :delete,
                                    data: { confirm: t('.are_you_sure?') },
                                    class: 'btn btn-danger'

= will_paginate @wishlists, list_classes: %w(pagination justify-content-center)

app/views/wishlists/new.html.slim
.row.justify-content-center
  .col-6
    h2= t('.new_wishlist')

    = render partial: 'form'

app/views/wishlists/products/_category_menu.html.slim
li.list-group-item
  = link_to category.name, menu_path(filter_by_category: category.id)
  - if category.children.any?
    = link_to '#', data: { toggle: 'collapse', target: "##{category.name.parameterize}" } do
      span.badge.badge-dark.float-right
        span.fa.fa-chevron-down.fa-menu

- if category.children.any?
  .list-group.list-group-child.collapse[id=category.name.parameterize]
    - category.children.each do |child|
      = render 'category_menu', category: child

app/views/wishlists/products/_product.html.slim
.card.product-card
  = image_tag('no-image', class: 'card-img-top product-image')
  .card-body
    .card-text
      small.text-truncate.product-name= product.name
      p= number_to_currency(product.price)
      = link_to t('.add'), wishlist_product_create_path(wishlist_id: @wishlist.id,
                                                        product_id: product.id),
                           method: :post,
                           class: 'btn btn-sm btn-outline-success'

app/views/wishlists/products/_products.html.slim
- @products.each do |product|
  = render 'product', product: product

app/views/wishlists/products/index.html.slim
.row
  .col-lg-3.col-sm-12
    ul.list-group.list-group-root
      li.list-group-item= link_to t('.all_categories'),
                                  wishlist_products_path(@wishlist)
      - @categories.each do |category|
        = render 'shared/category_menu', category: category

  .col-lg-9.col-sm-12
    .row
      .col-6
        h4= t('.products_of_wishlist', wishlist: @wishlist.name)
      .col-6
        .float-right
          = link_to t('.add_product'), new_wishlist_product_path(@wishlist),
                                       class: 'btn btn-sm btn-primary'
    - if @filtered_by_category.present?
      .row
        .col-12
          p= t('.filtering_by', category: @filtered_by_category.name)

    #products.row
      = render 'product_wishlists/product_wishlists'
    .row.justify-content-center
      .infinite-scrolling
        = will_paginate @product_wishlists

app/views/wishlists/products/index.js.erb
$('#products').append('<%= j render 'product_wishlists' %>');
<% if @product_wishlists.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @product_wishlists %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/wishlists/products/new.html.slim
.row
  .col-lg-3.col-sm-12
    ul.list-group.list-group-root
      li.list-group-item= link_to t('.all_categories'),
                                  new_wishlist_product_path(@wishlist)
      - @categories.each do |category|
        = render 'category_menu', category: category

  .col-lg-9.col-sm-12
    .row
      .col-6
        h4= t('.add_product_to_wishlist', wishlist: @wishlist.name)
      .col-6
        .float-right
          = link_to t('.back_to_wishlist'), wishlist_products_path(@wishlist),
                                            class: 'btn btn-sm btn-primary'
    - if @filtered_by_category.present?
      .row
        .col-12
          p= t('.filtering_by', category: @filtered_by_category.name)

    #products.row
      = render 'products'
    .row.justify-content-center
      .infinite-scrolling
        = will_paginate @products

app/views/wishlists/products/new.js.erb
$('#products').append('<%= j render 'products' %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @products %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>